# Generated by Django 5.2.10 on 2026-01-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_book_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='book',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
