# Generated by Django 5.2.10 on 2026-03-11 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_book_categories_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='Legacy field - use author_fk instead', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_by_fk', to='store.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, help_text='Legacy field - use category_fk instead', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_by_fk', to='store.category'),
        ),
    ]
