# Generated by Django 5.2.13 on 2026-05-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_rename_book_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('book', 'Book'), ('clothing', 'Clothing'), ('electronics', 'Electronics'), ('mobile', 'Mobile'), ('home_appliance', 'Home Appliance'), ('beauty', 'Beauty'), ('food', 'Food'), ('furniture', 'Furniture'), ('sports', 'Sports'), ('toys', 'Toys')], db_index=True, default='book', max_length=20),
        ),
        migrations.AlterModelTable(
            name='product',
            table='store_product',
        ),
        migrations.AlterModelTable(
            name='productdetail',
            table='store_productdetail',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='store_productimage',
        ),
    ]

